---
kind: pipeline
name: default

steps:
- name: test
  image: maven:3.6-jdk-11
  commands:
  - mvn package -DskipTests
---
kind: pipeline
name: deploy

steps:
- name: Docker build
  image: plugins/docker
  settings:
    repo: neticdk/helidon-demo
