---
kind: pipeline
name: default
type: kubernetes

steps:
- name: test
  image: maven:3.6-jdk-11
  commands:
  - mvn package -DskipTests
---
kind: pipeline
name: deploy
type: kubernetes

steps:
- name: Docker build
  image: plugins/docker
  settings:
    repo: langecode/helidon-demo-drone
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
