---
kind: pipeline
name: default
type: kubernetes

steps:
- name: test
  image: maven:3.8-jdk-11@sha256:805f366910aea2a91ed263654d23df58bd239f218b2f9562ff51305be81fa215
  commands:
  - mvn package -DskipTests
---
kind: pipeline
name: deploy
type: kubernetes

steps:
- name: Docker build
  image: plugins/docker@sha256:4e482ef91fb2695d658a85c60772d7f75f931e0883e23ec0954f0bc17ccc0663
  settings:
    repo: langecode/helidon-demo-drone
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
