kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "netic-demo.fullname" . }}
  labels: {{ include "netic-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "netic-demo.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "netic-demo.labels" . | nindent 8 }}
    spec:
      containers:
      - name: helidon-quickstart-mp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
      securityContext:
        runAsUser: 65534
