{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "netic-demo.fullname" . }}
  labels: {{ include "netic-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "netic-demo.matchLabels" . | nindent 6 }}
  endpoints:
  - port: http
{{- end }}
