apiVersion: v1
kind: Service
metadata:
  name: {{ template "netic-demo.fullname" . }}
  labels: {{ include "netic-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ include "netic-demo.matchLabels" . | nindent 4 }}
